### ISSUE TITLE
Do i have to use all providers?

### ISSUE THREAD

**Issue by axelvnk** [1001Pharmacies/geolocation-bundle#21]
Hi,

I tried out the bundle, but seems like you have to use all providers? I just want long and lat from google maps. But because I only set the google maps api key in my parameters.yml, there are unauthorized requests being sent to http://dev.virtualearth.net/REST/v1/ , which is Bing I presume..

**Comment by methylbro** [comment]
That's right.
Actually I'm using all of this services. So I do not anticipate your case.

We could imagine a way to load configured providers only.
Somewhere in the Extension class (https://github.com/1001Pharmacies/geolocation-bundle/blob/master/DependencyInjection/MeupGeoLocationExtension.php#L147).
Feel free to contribute to it :)

**Comment by axelvnk** [comment]
Okay, seems like something easy to do. I'll fork and see if i can free up some time any soon.

**Comment by methylbro** [comment]
Hi @axelvnk 

I worked on a feature that will allow you to use/do not use providers of your choice.
https://github.com/1001Pharmacies/geolocation-bundle/pull/22

That would be helpful to you ?

**Comment by axelvnk** [comment]
@methylbro nice, well done! If this gets merged and released I'll adjust my composer.json for the project I used it for.

**Comment by methylbro** [comment]
merged. Try with the v1.0.4 in your composer :)
https://github.com/1001Pharmacies/geolocation-bundle/releases/tag/v1.0.4
