### ISSUE TITLE
Set default provider

### ISSUE THREAD

**Issue by kmonmousseau** [1001Pharmacies/geolocation-bundle#9]
We should be able to request another provider if the selected one returns nothing.

**Comment by methylbro** [comment]
What we should do : 

First, create two exceptions : 
```php
namespace Meup\Bundle\GeoLocationBundle\Exception;

class NoResultException {}
class ProviderQuotaExceedException {}
```

The `Meup\Bundle\GeoLocationBundle\Handler\Locator::getCoordinates()` and `Meup\Bundle\GeoLocationBundle\Handler\Locator::getAddress()` methods should throws this exceptions.

And then, we should update the `Meup\Bundle\GeoLocationBundle\Handler::locate()` method : 

```php
    public function locate(LocationInterface $location)
    {
        $result   = null;
        $locators = $this->locators;

        do {
            $key     = rand(0, count($locators)-1);
            $locator = $locators[$key];

            try {
                $result = $locator->locate($location);
            } catch (NoResultException $e) {
                // don't continue if the given location does not exists ...
                break;
            } catch (ProviderQuotaExceedException $e) {
                unset($locators[$key]);
            }
        } while (!empty($locators) && $result===null);

        // ...

        return $result;
    }
```

I'm not certain that is pertinent to ask to every available providers a location that a first one asn't found yet.

**Comment by kmonmousseau** [comment]
I have a case where osm doesn't return anything but gmaps returns a result:
`"rue de thor, 34000 montpellier"`

Google finds something but for osm the road is `"rue du thor"`, hence nothing is returned...
